FeatureModel: FeatureModel/*.java
	javac FeatureModel/*.java

test: TestFeatureModel.java
	javac TestFeatureModel.java
	java -ea TestFeatureModel

clean:
	rm FeatureModel/*.class
	rm TestFeatureModel.class